In [109]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Задание 1

Необходимо сравнить скорость создания одномерного массива c помощью встроенных функций zeros(), ones(), empty() в Python.

В Google Colab для получения времени выполнения кода каждой ячейки удобно воспользоваться функцией %%time. Например:

In [110]:
%%time 
np.array([1,4,5,3,4,3,3])

CPU times: total: 0 ns
Wall time: 0 ns


array([1, 4, 5, 3, 4, 3, 3])

Создайте три одномерных массива размерностью 100, используя каждую из вышеперечисленных функций, и напишите полученные результаты Wall time.
Полученные результаты следует писать через запятую в порядке перечисленных выше функций (т.е. сначала для zeros(), потом для ones(), в конце для empty()). 

In [111]:
%%time 
np.zeros(100000)

CPU times: total: 0 ns
Wall time: 0 ns


array([0., 0., 0., ..., 0., 0., 0.])

In [112]:
%%time 
np.ones(100000)

CPU times: total: 0 ns
Wall time: 0 ns


array([1., 1., 1., ..., 1., 1., 1.])

In [113]:
%%time 
np.empty(100000)

CPU times: total: 0 ns
Wall time: 0 ns


array([7.43545888e-312, 7.91829874e-312, 0.00000000e+000, ...,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

Как видно из Wall time массив создается быстрее всего с помощью функции numpy.empty()

# Задание 2
Выберите из предложенных ниже тот вариант (варианты) кода на языке Python, результатом выполнения которого является следующее: array([1., 1., 1., 1.]) 

In [114]:
np.linspace(1,1,4)

array([1., 1., 1., 1.])

In [115]:
np.ones(4)

array([1., 1., 1., 1.])

In [116]:
np.array([1,1,1,1.0])

array([1., 1., 1., 1.])

In [117]:
np.ones(4, dtype=np.float64)

array([1., 1., 1., 1.])

# Задание 3
При помощи Python реализуйте функцию с именем new_arr(arr, list1), которая добавляет в одномерный массив arr список list1. Возвращать функция должна тип данных получившегося массива и его длину. 

In [118]:
import numpy as np
def new_arr(arr, list1):
    ret_arr = np.append(arr, list1)
    return ret_arr.dtype, np.shape(ret_arr)[0]

In [119]:
arr = np.array([23, 34])

In [120]:
type, arr = new_arr(arr, [234, 3])

In [121]:
type

dtype('int32')

In [122]:
arr

4

Данный вариант не подошел в тесте, поэтому попробуем другой вариант:

In [123]:
def new_arr(arr, list1):
	arr = np.append(arr, list1)
	return arr.dtype,len(arr) 

In [124]:
type, arr = new_arr(arr, [234, 3])

In [125]:
type

dtype('int32')