In [8]:
import numpy as np

# Задание 1

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [11]:
arr[2]

array([7, 8, 9])

In [12]:
arr[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
arr[1, :2]

array([4, 5])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Задание 2
Напишите разультаты выполнения кода, написанного на языке Python.
Выведите размерность .size массива np.append(np.zeros((2,2)),np.array([[1,2],[4,5]])):

In [16]:
np.shape(np.append(np.zeros((2,2)),np.array([[1,2],[4,5]])))

(8,)

In [19]:
np.append(np.zeros((2,2)),np.array([[1,2],[4,5]])).size

8

Выведите количество строк массива np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]),axis = 1):

In [20]:
np.shape(np.append(np.zeros((2,2)),np.array([[1,2],[4,5]]),axis = 1))

(2, 4)

Выведите значение последнего элемента массива np.sort(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0),axis = 0):

In [21]:
np.sort(np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0),axis = 0)[-1, -1]

4

Сколько элементов будет выведено в результате суммирования np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0).sum(axis = 1):

In [24]:
np.append(np.array([[1,2],[3,0]]),np.array([[1,2],[5,4]]),axis = 0).sum(axis = 1).size

4